### ISSUE TITLE
directory index of "/srv/www/" is forbidden

### ISSUE THREAD

**Issue by smyth64** [lewg/wordpress-docker#1]
Hi,
I am running your Docker Compose on my Mac.

When I try to start and go to docker.dev:8000, I get 403 forbidden.

nginx tell me:
web_1 | 2015/11/28 22:27:53 [error] 10#10: *1 directory index of "/srv/www/" is forbidden, client: 192.168.99.1, server: localhost, request: "GET / HTTP/1.1", host: "docker.dev:8000"

Whats the matter?

**Comment by smith64fx** [comment]
forgot to install wp :)

**Comment by smyth64** [comment]
i had to restart the docker machine

**Comment by lewg** [comment]
Usually I get that if something has gone awry with the NFS share.

**Comment by smyth64** [comment]
I think its because of docker-osx-dev
Am 04.12.2015 21:55 schrieb "Lew Goettner" notifications@github.com:

**Comment by lewg** [comment]
For what it's worth, I ended a lot of my NFS pain on OSX by switching to a non-udp NFS mount in Vagrant. 

```
config.vm.synced_folder ENV['HOME'], ENV['HOME'], id: "home", :nfs => true, :nfs_udp => false, :mount_options => ['nolock,vers=3']
```

Your milage may vary!
