### ISSUE TITLE
Run behind automated reverse proxy?

### ISSUE THREAD

**Issue by avidsapp** [lewg/wordpress-docker#4]
Hi. This is a great looking repo. Is there a way to support SSL behind a nginx reverse proxy similar to [this tutorial](https://cianallner.com/ultimate-wordpress-docker-setup-guide/)? I received a `RequestInitDocument Not Found` error when attempting.

**Comment by lewg** [comment]
You'll need to overwrite the default nginx conf. I don't see why it wouldn't work though, I have custom nginx configs for all the sites I run this way (disclaimer: I run behind an ELB though, so they're not doing SSL). Usually, it's just an `ADD default.conf /etc/nginx/conf.d/default.conf, although in your case you'll need to add the cert files as well.

**Comment by avidsapp** [comment]
Just to be clear: overwrite with a blank default.conf by adding `ADD default.conf /etc/nginx/conf.d/default.conf` to the proxy Dockerfile? I believe this can also be acheived via [derived image or mounting the file](https://github.com/jwilder/nginx-proxy/blob/master/README.md#proxy-wide).

Add the cert files? Is this not accomplished by mounting the volumes:

```
...
  volumes:
    - /home/<username>/certs:/etc/nginx/certs:ro
...
```
